version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
      - MONGODB_URL=mongodb+srv://isankauvini:6QkA619zPsGMXF6H@carpark.ewfdqnk.mongodb.net/?retryWrites=true&w=majority&appName=Carpark
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5555
    depends_on:
      - backend


# //docker-compose.yml